import os
import json
import time
from dotenv import load_dotenv
from google import genai

# Load environment variables
load_dotenv()

# Configure Gemini
client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY")
)


def evaluate_pronunciation(audio_path, transcript):

    prompt = f"""
You are an expert English pronunciation evaluator.

The attached file is an English speech recording.

A transcript generated by Whisper is provided below.

Transcript:
{transcript}

IMPORTANT:
- Analyze the AUDIO as the primary source of truth.
- Use the transcript only as supporting context because it may contain transcription errors.
- Do NOT invent pronunciation mistakes.
- If pronunciation is clear, return an empty list for "mispronounced_words".

Evaluate the speaker on:

1. Overall Score (0-100)
2. Pronunciation Score (0-100)
3. Fluency Score (0-100)
4. Clarity Score (0-100)
5. Speaking Pace (Too Slow / Good / Too Fast)
6. Mispronounced Words
7. Speaker Strengths
8. Suggestions for Improvement
9. Overall Feedback
10. Correct only obvious transcription errors in the Whisper transcript.

Rules:
- Preserve the speaker's original words whenever possible.
- Do NOT rewrite or paraphrase the sentence.
- Do NOT improve grammar unless it is clearly a transcription mistake.
- Correct only obvious recognition errors (for example, names, punctuation, or incorrectly recognized words).
- If the transcript is already correct, return it unchanged.

{{
  "corrected_transcript": "Hi, my name is Muskan Kumari.",
  "overall_score": 91,
  "pronunciation_score": 92,
  "fluency_score": 90,
  "clarity_score": 94,
  "pace": "Good",
  "mispronounced_words": [
    {{
      "word": "artificial",
      "severity": "Medium",
      "issue": "Weak stress on the third syllable.",
      "tip": "Stress the 'fi' syllable."
    }}
  ],
  "strengths": [
    "Clear vowel sounds",
    "Good speaking confidence"
  ],
  "suggestions": [
    "Practice stress on longer words.",
    "Slow down slightly."
  ],
  "overall_feedback": "Overall very good pronunciation with minor improvements needed."
}}

Rules:
1. Return ONLY JSON.
2. Do NOT use markdown.
3. Do NOT use code blocks.
4. Do NOT explain your answer.
5. Always return valid JSON.
"""  
    try:

        # Upload audio to Gemini
        uploaded_file = client.files.upload(file=audio_path)

        print("=" * 50)
        print("Audio uploaded successfully")
        print("File Name:", uploaded_file.name)
        print("Initial State:", uploaded_file.state.name)
        print("=" * 50)

        # Wait for Gemini to process the file
        for attempt in range(30):

            uploaded_file = client.files.get(name=uploaded_file.name)

            print(f"Attempt {attempt + 1}")
            print("Current State:", uploaded_file.state.name)

            if uploaded_file.state.name == "ACTIVE":
               print("File is ACTIVE!")
               break

            if uploaded_file.state.name == "FAILED":
               raise Exception("Gemini failed to process the uploaded file.")

            time.sleep(2)

        else:
            raise Exception("Timed out waiting for Gemini to process the file.")

    # Generate pronunciation evaluation
        response = client.models.generate_content(
           model="gemini-2.5-flash",
           contents=[
              uploaded_file,
              prompt
           ]
       )

        text = response.text.strip()

    # Delete uploaded file from Gemini
        client.files.delete(name=uploaded_file.name)

    # Remove markdown if Gemini returns it
        text = text.replace("```json", "").replace("```", "").strip()

        return json.loads(text)

    except Exception as e:
        return {
        "error": str(e)
    }